### ISSUE TITLE
TypeError when options parameter is not provided

### ISSUE THREAD

**Issue by riddla** [ChrisCavs/bounds.js#1]
When invoking bound.js without an options parameter like ...

`
const windowBound = Bounds();
`

... I get the error `bounds.js:1 Uncaught TypeError: Cannot read property 'root' of undefined`.

Using an empty param (`const windowBound = Bounds({});`) as a workaround.

**Comment by ChrisCavs** [comment]
I pushed an update (v1.0.4) that fixes this issue, thank you for bringing it to my attention!
